import Anthropic from '@anthropic-ai/sdk';
import { env } from '../config/envConfig';
import { logger } from '../utils/logger';
import { ClaudeScoringResult, ScamCategory, CallVerdict } from '../types/backend.types';
import { SCAM_DETECTION_SYSTEM_PROMPT, buildScamAnalysisPrompt } from '../prompts/scamDetectionPrompt';

export class ClaudeScoringService {
  private client: Anthropic | null = null;

  constructor() {
    if (env.ANTHROPIC_API_KEY) {
      this.client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });
    }
  }

  /**
   * Score a live transcript chunk in context of full conversation history using Claude
   */
  public async scoreTranscriptChunk(
    transcriptChunk: string,
    fullTranscriptHistory: string = '',
    callerNumber?: string
  ): Promise<ClaudeScoringResult> {
    if (!this.client) {
      logger.warn('ANTHROPIC_API_KEY is not configured. Using local rule-based heuristic evaluator.');
      return this.localFallbackEvaluation(transcriptChunk, fullTranscriptHistory);
    }

    try {
      const userPrompt = buildScamAnalysisPrompt(transcriptChunk, fullTranscriptHistory, callerNumber);
      
      const response = await this.client.messages.create({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 500,
        temperature: 0.1,
        system: SCAM_DETECTION_SYSTEM_PROMPT,
        messages: [{ role: 'user', content: userPrompt }],
      });

      const textBlock = response.content.find((c: any) => c.type === 'text');
      if (!textBlock || !('text' in textBlock)) {
        throw new Error('Claude response did not contain text content');
      }

      // Extract JSON if wrapped in markdown code fence
      let jsonStr = (textBlock as any).text.trim();
      if (jsonStr.startsWith('```json')) {
        jsonStr = jsonStr.replace(/^```json\s*/, '').replace(/\s*```$/, '');
      } else if (jsonStr.startsWith('```')) {
        jsonStr = jsonStr.replace(/^```\s*/, '').replace(/\s*```$/, '');
      }

      const parsed = JSON.parse(jsonStr);
      const score = Math.min(100, Math.max(0, typeof parsed.score === 'number' ? parsed.score : 0));
      
      let verdict: CallVerdict = 'Legitimate';
      if (score >= 75) verdict = 'Fraudulent';
      else if (score >= 40) verdict = 'Suspicious';

      return {
        score,
        verdict: parsed.verdict || verdict,
        category: (parsed.category as ScamCategory) || (score >= 75 ? 'OTP_THEFT' : 'SAFE'),
        triggerPhrases: Array.isArray(parsed.triggerPhrases) ? parsed.triggerPhrases : [],
        modelExplanation: parsed.modelExplanation || 'Analysis generated by Anthropic Claude NLP engine.',
        confidence: typeof parsed.confidence === 'number' ? parsed.confidence : 0.92,
      };
    } catch (err) {
      logger.error('Error invoking Anthropic Claude API, using fallback evaluator', err);
      return this.localFallbackEvaluation(transcriptChunk, fullTranscriptHistory);
    }
  }

  /**
   * Local rule-based analyzer when API is unavailable or offline
   */
  private localFallbackEvaluation(chunk: string, history: string): ClaudeScamAnalysisFallback {
    const text = `${history} ${chunk}`.toLowerCase();
    const lowerChunk = chunk.toLowerCase();

    // 1. Customs Parcel & Police / Digital Arrest Threats
    if (
      text.includes('parcel') && 
      (text.includes('customs') || text.includes('mdma') || text.includes('drugs') || text.includes('police') || text.includes('digital arrest') || text.includes('narcotics'))
    ) {
      return {
        score: 95,
        verdict: 'Fraudulent',
        category: 'CUSTOMS_PARCEL_SCAM',
        triggerPhrases: ['customs parcel seized', 'narcotics found', 'digital arrest', 'illegal package'],
        modelExplanation: 'Impersonating customs or law enforcement with false accusations of drug parcels and coercive extortion.',
        confidence: 0.98,
      };
    }

    // 2. OTP & Banking Credential Theft
    if (
      lowerChunk.includes('otp') || 
      lowerChunk.includes('verification code') || 
      lowerChunk.includes('6 digit') || 
      lowerChunk.includes('share the code') ||
      lowerChunk.includes('cvv')
    ) {
      return {
        score: 92,
        verdict: 'Fraudulent',
        category: 'OTP_THEFT',
        triggerPhrases: ['share OTP', 'verification code', '6 digit code'],
        modelExplanation: 'Direct demand for SMS OTP or security verification codes to execute unauthorized banking transactions.',
        confidence: 0.96,
      };
    }

    // 3. Fake Bank KYC / Account Expiry Disconnection
    if (
      (text.includes('kyc') || text.includes('pan card') || text.includes('electricity') || text.includes('sim deactivation')) &&
      (text.includes('block') || text.includes('expired') || text.includes('suspended') || text.includes('cut off') || text.includes('tonight'))
    ) {
      return {
        score: 86,
        verdict: 'Fraudulent',
        category: 'KYC_EXPIRY',
        triggerPhrases: ['KYC expired', 'account suspended', 'power disconnected', 'update immediately'],
        modelExplanation: 'Artificial panic creation claiming immediate account freeze or utility cutoff unless instant action is taken.',
        confidence: 0.94,
      };
    }

    // 4. UPI Refund / Payment Link Trap
    if (
      (text.includes('upi') || text.includes('refund') || text.includes('cashback') || text.includes('phonepe') || text.includes('gpay')) &&
      (text.includes('pin') || text.includes('pay button') || text.includes('click link') || text.includes('claim credit'))
    ) {
      return {
        score: 88,
        verdict: 'Fraudulent',
        category: 'UPI_FRAUD',
        triggerPhrases: ['enter UPI PIN', 'click pay button to receive', 'claim cashback'],
        modelExplanation: 'Tricking victim into approving UPI payment requests under false premise of receiving incoming money or refunds.',
        confidence: 0.95,
      };
    }

    // 5. Authority Impersonation (TRAI, Telecom, Bank Manager)
    if (
      lowerChunk.includes('calling from trai') || 
      lowerChunk.includes('bank manager') || 
      lowerChunk.includes('head office') || 
      lowerChunk.includes('mumbai cyber cell')
    ) {
      return {
        score: 65,
        verdict: 'Suspicious',
        category: 'IMPERSONATION',
        triggerPhrases: ['calling from head office', 'police officer', 'official verification'],
        modelExplanation: 'Unverified authority claim attempting to establish false legitimacy before requesting sensitive information.',
        confidence: 0.88,
      };
    }

    // 6. Food Delivery / Safe Call
    if (
      text.includes('swiggy') || 
      text.includes('zomato') || 
      text.includes('delivery') || 
      text.includes('gate') || 
      text.includes('dinner') || 
      text.includes('reach home') ||
      text.includes('otp for delivery')
    ) {
      return {
        score: 8,
        verdict: 'Legitimate',
        category: 'SAFE',
        triggerPhrases: [],
        modelExplanation: 'Routine food delivery or personal conversational dialogue. No social engineering indicators observed.',
        confidence: 0.98,
      };
    }

    // Default Safe/Low
    return {
      score: 12,
      verdict: 'Legitimate',
      category: 'SAFE',
      triggerPhrases: [],
      modelExplanation: 'General conversation with zero immediate financial extortion or coercion signals detected.',
      confidence: 0.85,
    };
  }
}

type ClaudeScamAnalysisFallback = ClaudeScoringResult;

export const claudeScoringService = new ClaudeScoringService();
